from .music import *  # noqa
from .browser import *  # noqa
from .system import *  # noqa
from .power import *  # noqa
from .screen import *  # noqa
from .jokes import *  # noqa
from .cleaner import *  # noqa
from .volume import *  # noqa
from .time_date import *  # noqa
from .apps import *  # noqa
from .modes import *  # noqa
